name: Bug report
description: File a bug report to help us improve.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        - Check to make sure someone hasn't already opened a similar [issue](https://github.com/sqlchat/sqlchat/issues).
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To reproduce
      description: A code snippet to reproduce the problem described above.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context, screenshots, videos or log files about the bug.
    validations:
      required: false
